### ISSUE TITLE
Issue: Errors Encountered During Execution of botprogram.py

### ISSUE THREAD

**Issue by Akshat21230** [perfinfer/code#1]
I am facing multiple issues while running the botprogram.py script in the Android Termux environment for the offline phase of perfinfer. Below are the steps I followed and the specific errors encountered:
Steps Taken:
    1. Placed the entire autotest directory in the Android Termux environment.
    2. Manually obtained coordinates for all relevant keys from the keyboard being tested and updated virtual_keyboard_location.txt accordingly.
    3. Adjusted the APP_LOC variable in botprogram.py to provide the coordinates of the text input field in the App.
    4. Ran cmake and make to compile the GPU PC collecting program.
    5. Attempted to execute botprogram.py.

Errors Encountered:
    1. Missing TYPING_INTERVAL_FILE:
       In the work_init(), TYPING_INTERVAL_FILE is being read but it does not exist initially. This causes the script to fail. 
Tried workaround: If I change the reference to DATABASE_FILE just to proceed further, other issues arise.
    2. Permission Error with RUNNING_BINARY_FILE:
       In the findmatch(), when the code tries to run the RUNNING_BINARY_FILE (./app), I encounter the following error: read: operation not permitted.

Additionally, I have attached are screenshots detailing the errors for reference.
![Screenshot_20240528-174907](https://github.com/pittisl/perfinfer-code/assets/108210209/78f26e56-a05c-4646-a37b-840be2a477bb)

Thanks for your attention. Kindly look into the same.

**Comment by hosiet** [comment]
Please make sure that your Android version is of the same version as in our paper (Android 11), and the OS being old enough so that it does not contain the Feb 2023 security fix. Check the OS security level in Config -> About phone -> Android version -> Android security update.

Google mitigated fixed this security flaw since Feb 2023 security update, and any newer OS will not be able to make use of our code.

**Comment by Akshat21230** [comment]
Thanks for the clarification.
